### GET ALL PERSONS
GET http://localhost:3001/api/persons/

### GET ONE PERSON
GET http://localhost:3001/api/persons/1692889063117

### CREATE NEW PERSON
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
  "name": "Peantu Butter",
  "number": "4"
}

### DELETE PERSON
DELETE http://localhost:3001/api/persons/1692889250310