### GET ALL PERSONS
GET http://localhost:3001/api/persons/

### GET ONE PERSON
GET http://localhost:3001/api/persons/64e8d030e991a6b7ea297820

### CREATE NEW PERSON
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
  "name": "SHORE MCGORE",
  "number": "123"
}

### UPDATE PERSON
PUT http://localhost:3001/api/persons/64e8d030e991a6b7ea297820
Content-Type: application/json

{
  "name": "PEANUT BUTTR",
  "number": "1234565677234213414123"
}

### DELETE PERSON
DELETE http://localhost:3001/api/persons/64e8ea70759ab3d4809a596