### GET ALL NOTES
GET http://localhost:3001/api/notes/

### GET NOTE BY ID
GET http://localhost:3001/api/notes/64e79b2616631d16c1a5e4f

### CREATE NOTE
POST http://localhost:3001/api/notes/
content-type: application/json

{
    "content": "DO NOT GIVE UP",
    "important": true
}

### DELETE NOTE
DELETE http://localhost:3001/api/notes/64ecb3e41086b23a344e83c9