# fly.toml app configuration file generated for aged-violet-7520 on 2023-08-23T13:28:55-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "aged-violet-7520"
primary_region = "mia"

[build]

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
